### ISSUE TITLE
magic.node - node/electron version (?) issue

### ISSUE THREAD

**Issue by peet86** [Thlb/MMM-synology-ds#1]
Hey, 

Thanks for this MMM module! It looks amazing, exactly what I need for my Mirror.. Unfortunately after the installation I received an error: 

`App threw an error during load
Error: The module '/home/pi/MagicMirror/modules/MMM-synology-ds/node_modules/mmmagic/build/Release/magic.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 48. This version of Node.js requires
NODE_MODULE_VERSION 53. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-synology-ds/node_modules/mmmagic/lib/index.js:3:13)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-synology-ds/node_modules/mmmagic/lib/index.js:32:3)
Whoops! There was an uncaught exception...
Error: The module '/home/pi/MagicMirror/modules/MMM-synology-ds/node_modules/mmmagic/build/Release/magic.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 48. This version of Node.js requires
NODE_MODULE_VERSION 53. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-synology-ds/node_modules/mmmagic/lib/index.js:3:13)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-synology-ds/node_modules/mmmagic/lib/index.js:32:3)
MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
Launching application.
`
I've tried to reinstall/rebuild it but it doesn't help at all. Do you have any idea how can I solve this issue? 

My setup: 
Raspberry Pi 3
Node: v.6.10.0
MMM: v2.1.0

Cheers, 
Peter

**Comment by zdeneksofr** [comment]
i'm a NOOB, so maybe stupid question - did you run "npm install" (in the module folder) to install support modules/functions (or for whatever it must be done)?

Zdeněk

**Comment by peet86** [comment]
Yes I did. 
@Thlb: have you tested this module with different node versions? What's the recommended version?
@zdeneksofr: As I see from your comment at the other issue the module itself is working for you, right? What's your node version?

**Comment by zdeneksofr** [comment]
@peet86 as `git pull` says "_already have latest version_" I guess I've latest published (I've no idea, how to check version). DSM 6.1.1-15101 Update 3

**Comment by Thlb** [comment]
Hi,

Sorry for this late answer. I cannot test with my raspberry right now, but i've already saw this error/bug with others modules. Take a look at : [https://forum.magicmirror.builders/topic/1263/toothbrush-integration/22](https://forum.magicmirror.builders/topic/1263/toothbrush-integration/22) (Module version mismatch-Error).

I'll test to reinstall my module as soon as possible to find a solution!

**Comment by zdeneksofr** [comment]
@Thlb this I found, and by this I solved. Now I've just problem mentioned upside.... module works, but says there is no DS with this config.....

Z

**Comment by Thlb** [comment]
@zdeneksofr 

Hi,

There was an error on the README... The "login" parameter doesn't exists, it's : "user".

So replace "login: 'user'," by "user: 'user'," and it should work :)

Hope this will solve your issue !

**Comment by sdetweil** [comment]
more than likely this is a mismatch between the electron node version and the mmmagic library used by this module

to fix do

cd ~/MagicMirror
npm install electron-rebuild
cd ~/MagicMirror/modules/MMM-synology-ds/node_modules/mmmagic
~/MagicMirror/node_modules/.bin/electron-rebuild

**Comment by TAGinside** [comment]
Hello, I am starting a new installation today with DSM 7.2,

and here is what I had to do in addition to installing the module.

I had to install the colors dependency:

`cd ~/MagicMirror/modules/MMM-synology-ds`
`npm install colors`

Then I tried to do what @sdetweil recommended: 

`cd ~/MagicMirror`
`npm install electron-rebuild`
`cd ~/MagicMirror/modules/MMM-synology-ds/node_modules/mmmagic`
`~/MagicMirror/node_modules/.bin/electron-rebuild`

I still get the same error: 

[ERROR] Error when loading MMM-synology-ds: The module ‘/home/TAGinside/MagicMirror/modules/MMM-synology-ds/node_modules/mmmagic/build/Release/magic.node’
was compiled against a different Node.js version using
NODE_MODULE_VERSION 131. This version of Node.js requires
NODE_MODULE_VERSION 128. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).

i have tryed npm rebuild but nothing


Translated with [DeepL.com](https://www.deepl.com/?utm_campaign=product&utm_source=web_translator&utm_medium=web&utm_content=copy_free_translation) (free version)
