### ISSUE TITLE
MM doesn't start after install this module

### ISSUE THREAD

**Issue by zdeneksofr** [Thlb/MMM-synology-ds#3]
I've did install, also npm install, asl get all patches/updates of Jessie... adding rows to config.js make  MM freeze, not possible to even quit, I had to remove power from RP3
```
		{
  		module: 'MMM-synology-ds',
    		position: 'bottom_right',
    		header: 'Stahování',
    		config: {
     		 	host: 'local_ip',
      			port: '5000', // Server port (not required if default port (5000) is used)
      			login: 'user',
      			passwd: 'pass',
      			refreshInterval: 60, // in seconds
      			compactMode: true, // recommanded in left or right position.
  		 	}
  		},
```
tried login via web to "local_ip" with "user" and "pass" on default 5000 port - works. idea?

Zdeněk

**Comment by zdeneksofr** [comment]
Error: Module version mismatch. Expected 50, got 48.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-synology-ds/node_modules/mmmagic/lib/index.js:3:13)
Whoops! There was an uncaught exception...
Error: Module version mismatch. Expected 50, got 48.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-synology-ds/node_modules/mmmagic/lib/index.js:3:13)

**Comment by zdeneksofr** [comment]
solved by 
npm rebuild --runtime=electron --target=1.4.0 --disturl=https://atom.io/download/atom-shell --build-from-source
